name: Run VSCode Extension Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Compile
        run: yarn  build
      - name: Run unit tests
        run: yarn ci
      - name: Run tests
        run: xvfb-run -a yarn e2e-test
